export const projects = [
  {
    id: 1,
    num: "01",
    status: "In Progress",
    statusColor: "#ffcc00",
    name: "Client-Server based Calc",
    subtitle: "Client-Server Computing",
    category: "Backend",
    desc: "A multi-threaded client-server application for mathematical computations using advanced socket programming in C.",
    highlights: ["Socket Programming", "Multi-threading", "C Networking", "Client-Server Architecture"],
    tech: ["C", "Sockets", "Multi-threading", "Networking"],
    detail: "This project implements a robust communication protocol between a central server and multiple clients, allowing concurrent mathematical processing and data synchronization.",
    github: "https://github.com/Neel092/socket-based-client-server-calculator",
    live: null,
  },
  {
    id: 2,
    num: "02",
    status: "Done",
    statusColor: "#00cc66",
    name: "CodePulse",
    subtitle: "Algorithm Progress Dashboard",
    category: "Fullstack",
    desc: "A feature-rich dashboard built to track coding progress across platforms, featuring data visualization and performance analytics.",
    highlights: ["MERN Stack", "Data Visualization", "Analytics", "Progress Tracking"],
    tech: ["React", "Node.js", "Express", "MongoDB", "Recharts"],
    detail: "Developed a comprehensive system to monitor DSA preparation, integrated with performance metrics and structured problem-solving sheets.",
    github: "https://github.com/Neel092/CodePulse",
    live: "#",
  },
  {
    id: 3,
    num: "03",
    status: "Live",
    statusColor: "#0099ff",
    name: "Dev Portfolio",
    subtitle: "Cinematic Web Experience",
    category: "Frontend",
    desc: "A premium, high-performance portfolio featuring glassmorphic design, fluid animations, and a cinematic aesthetic.",
    highlights: ["Framer Motion", "Glassmorphism", "Vite", "Modern UI/UX"],
    tech: ["React", "Framer Motion", "Vite", "Vanilla CSS"],
    detail: "An editorial-grade web experience focused on smooth motion, high-contrast dark mode, and interactive storytelling.",
    github: "https://github.com/Neel092/neel.portfolio",
    live: "https://neelpatil.vercel.app/",
  },
  {
    id: 4,
    num: "04",
    status: "Done",
    statusColor: "#00cc66",
    name: "MediChain-AI",
    subtitle: "AI - Driven Health-Tech",
    category: "Fullstack",
    desc: "An advanced AI-powered health-tech platform designed to streamline medical records, automate insurance claims, and provide intelligent diagnostics.",
    highlights: ["Gemini API", "Framer Motion", "Glassmorphism", "Vite", "Modern UI/UX"],
    tech: ["React 18", "TypeScript 5", "Tailwind CSS 3", "Framer Motion", "Lucide Icons"],
    detail: "Developed an intelligent health-tech platform leveraging the Gemini API to revolutionize patient data management. The system automates insurance claims processing using AI, reducing manual workload and ensuring accuracy. It features advanced medical report analysis, extracting critical insights and generating summaries effortlessly. Additionally, an integrated diagnostic module assists healthcare professionals by providing preliminary health assessments based on patient data.",
    github: "https://github.com/Neel092/MediChain-AI",
  },
  {
    id: 5,
    num: "05",
    status: "Done",
    statusColor: "#00cc66",
    name: "Contact Book",
    subtitle: "Contact Management System",
    category: "Mobile",
    desc: "A contact management system built with Flutter that allows users to store and manage their contacts.",
    highlights: ["Mobile Application", " Framer Motion", "Glassmorphism", "Vite", "Modern UI/UX"],
    tech: ["Express.js", "MySQL", "JWT", "bcrypt", "multer", "csv-parser & json2csv", "React", "Axios", "Tailwind CSS"],
    detail: "Developed a contact management system built with Flutter that allows users to store and manage their contacts. It features a user-friendly interface, secure authentication, and efficient contact management.",
    github: "https://github.com/Neel092/contact_book",
  },
];
