import { C } from "./designTokens";

export const projects = [
  {
    id: 1,
    num: "01",
    status: "In Progress",
    statusColor: C.accent3,
    gradFrom: C.purple,
    gradTo: C.accent,
    name: "Client-Server based Calc",
    subtitle: "Client-Server Computing",
    desc: "A multi-threaded client-server application for mathematical computations using advanced socket programming in C.",
    highlights: ["Socket Programming", "Multi-threading", "C Networking", "Client-Server Architecture"],
    futureGoals: ["Thread Pool implementation", "ASIO", "Non-blocking io"],
    tech: ["C", "Sockets", "Multi-threading", "Networking"],
    detail: "This project implements a robust communication protocol between a central server and multiple clients, allowing concurrent mathematical processing and data synchronization.",
    github: "https://github.com/Neel092/socket-based-client-server-calculator",
    live: null,
  },
  {
    id: 2,
    num: "02",
    status: "In Progress",
    statusColor: C.accent,
    gradFrom: C.accent,
    gradTo: C.accent2,
    name: "DSA Tracker",
    subtitle: "Algorithm Progress Dashboard",
    desc: "A feature-rich dashboard built to track coding progress across platforms, featuring data visualization and performance analytics.",
    highlights: ["MERN Stack", "Data Visualization", "Analytics", "Progress Tracking"],
    tech: ["React", "Node.js", "Express", "MongoDB", "Recharts"],
    detail: "Developed a comprehensive system to monitor DSA preparation, integrated with performance metrics and structured problem-solving sheets.",
    github: "https://github.com/Neel092/DSA_Tracker",
    live: "#",
  },
  {
    id: 3,
    num: "03",
    status: "Live",
    statusColor: C.accent2,
    gradFrom: C.pink,
    gradTo: C.purple,
    name: "Dev Portfolio",
    subtitle: "Cinematic Web Experience",
    desc: "A premium, high-performance portfolio featuring glassmorphic design, fluid animations, and a cinematic aesthetic.",
    highlights: ["Framer Motion", "Glassmorphism", "Vite", "Modern UI/UX"],
    tech: ["React", "Framer Motion", "Vite", "Vanilla CSS"],
    detail: "An editorial-grade web experience focused on smooth motion, high-contrast dark mode, and interactive storytelling.",
    github: "https://github.com/Neel092/neel.portfolio",
    live: "https://neelpatil.vercel.app/",
  },
];
